### ISSUE TITLE
MkIssue#assignee() fails

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-github#1011]
This is what I'm doing:

```
        final Issue.Smart issue = new Issue.Smart(this.issue());
        issue.assign("walter");
        MatcherAssert.assertThat(
            issue.assignee().login(),
            Matchers.startsWith("wal")
        );
```

```
java.lang.ClassCastException: Cannot cast org.glassfish.json.JsonStringImpl to javax.json.JsonObject
	at java.lang.Class.cast(Class.java:3094)
	at com.jcabi.github.SmartJson.value(SmartJson.java:143)
	at com.jcabi.github.Issue$Smart.assignee(Issue.java:253)
	at com.jcabi.github.mock.MkIssueTest.assignsUser(MkIssueTest.java:249)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.10`
