### ISSUE TITLE
Issue.Smart.assignee() crashes

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-github#1012]
```
java.lang.ClassCastException: Cannot cast javax.json.JsonValue$1 to javax.json.JsonObject
	at java.lang.Class.cast(Class.java:3176)
	at com.jcabi.github.SmartJson.value_aroundBody6(SmartJson.java:143)
	at com.jcabi.github.SmartJson$AjcClosure7.run(SmartJson.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.github.SmartJson.value(SmartJson.java:120)
	at com.jcabi.github.Issue$Smart.assignee_aroundBody20(Issue.java:253)
	at com.jcabi.github.Issue$Smart$AjcClosure21.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.github.Issue$Smart.assignee(Issue.java:253)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.19`
