### ISSUE TITLE
NoClassDefFoundError during the build

### ISSUE THREAD

**Issue by asaen** [jcabi/jcabi-github#1167]
In latest merge logs there is a `NoClassDefFoundError`, I think we should fix it. [Example](http://www.rultor.com/t/4748-130215299):

```
[0;33mWARNm] pool-1-thread-10 org.reflections.Reflections: could not create Dir using commons_vfs2 from url file:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/libatk-wrapper.so. skipping. 
java.lang.NoClassDefFoundError: org/apache/commons/vfs2/VFS 
at org.reflections.vfs.Vfs$DefaultUrlTypes$7.matches(Vfs.java:281) 
at org.reflections.vfs.Vfs.fromURL(Vfs.java:97) 
at org.reflections.vfs.Vfs.fromURL(Vfs.java:90) 
at org.reflections.Reflections.scan(Reflections.java:236) 
at org.reflections.Reflections.scan(Reflections.java:203) 
at org.reflections.Reflections.<init>(Reflections.java:128) 
at com.jcabi.github.ClasspathRule.allTypes(ClasspathRule.java:61) 
at com.jcabi.github.ClasspathRule.allPublicMethods(ClasspathRule.java:112) 
at com.jcabi.github.NullabilityTest.checkNullability(NullabilityTest.java:76) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:606) 
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) 
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) 
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) 
at com.jcabi.github.ClasspathRule$2.evaluate(ClasspathRule.java:102) 
at org.junit.rules.RunRules.evaluate(RunRules.java:20) 
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) 
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) 
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) 
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) 
at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 
at java.util.concurrent.FutureTask.run(FutureTask.java:262) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs2.VFS 
at java.net.URLClassLoader$1.run(URLClassLoader.java:366) 
at java.net.URLClassLoader$1.run(URLClassLoader.java:355) 
at java.security.AccessController.doPrivileged(Native Method) 
at java.net.URLClassLoader.findClass(URLClassLoader.java:354) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:425) 
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
... 29 more
```

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by dmarkov** [comment]
@darkled thanks a lot for reporting, **15 mins** added to your acc, pmt ID `66334675`

**Comment by amihaiemil** [comment]
Closing for now; will reopen if we see it reproduce

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
