### ISSUE TITLE
Problem with rultor merge

### ISSUE THREAD

**Issue by pecko** [jcabi/jcabi-github#1169]
The PR https://github.com/jcabi/jcabi-github/pull/1162 fixes the issue #932 

Tests passed on my local machine, Travis and AppVeyor, but failed on rultor with the following messages:

The error in com.jcabi.github.RtIssueITCase talksInGithubProject(com.jcabi.github.RtIssueITCase:
```
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.552 sec <<< FAILURE! - in com.jcabi.github.RtIssueITCase talksInGithubProject(com.jcabi.github.RtIssueITCase) Time elapsed: 0.514 sec 
<<< ERROR! java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonString at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:194) at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199) at com.jcabi.github.User$Smart.name_aroundBody6(User.java:191) at com.jcabi.github.User$Smart$AjcClosure7.run(User.java:1) at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207) at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1) at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136) at com.jcabi.github.User$Smart.name(User.java:181) at com.jcabi.github.RtIssueITCase.talksInGithubProject(RtIssueITCase.java:107)
```

The failures:
```
Failed tests: RtContentsITCase.canUpdateFileContentInSpecificBranch:155 
Expected: "Updated" but: was "Initial.
" RtContentsITCase.canUpdateFileContent:110 
Expected: "new content" but: was "init content"  
Tests run: 116, Failures: 2, Errors: 1, Skipped: 5
```

**Comment by darkled** [comment]
@pecko it's a duplicate of #1168.

**Comment by pecko** [comment]
@darkled 

Rultor returns the error described in #1168, but also two failures.
I will keep this issue opened until fixing all errors/failures.

**Comment by pecko** [comment]
@darkled 

The failures don't happen in a new rultor merge. Closed as duplicate.
