### ISSUE TITLE
Lib crash when the 'login' name as passed could not be find during calling com.jcabi.github.Users.get()

### ISSUE THREAD

**Issue by linxingyun** [jcabi/jcabi-github#1220]
Run the following code : 

		try {
                        Github github = new RtGithub(access_token);
			JsonObject userJsonObject = github.users().get("boluo408").json();
		} catch (Exception ex) {
			ex.printStackTrace();
		}

The jcabi-github lib will crash. Following is the detail log:

```
23:58:53.335 [1;31mERROR[0;39m [main] [36mcom.jcabi.github.RtJson[0;39m - #fetch(): thrown java.lang.AssertionError(HTTP response status is not equal to 200:
404 Not Found [https://api.github.com/users/boluo408]
Server: GitHub.com
Date: Thu, 31 Mar 2016 15:58:52 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4729
X-RateLimit-Reset: 1459442941
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, repo, user
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: DDDE0D97:1805C:DA35060:56FD493A

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
Expected: HTTP response with status 200
     but: was <404 Not Found [https://api.github.com/users/boluo408]
Server: GitHub.com
Date: Thu, 31 Mar 2016 15:58:52 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4729
X-RateLimit-Reset: 1459442941
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, repo, user
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: DDDE0D97:1805C:DA35060:56FD493A

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}>) out of org.hamcrest.MatcherAssert#assertThat[20] in 10s
23:58:53.338 [1;31mERROR[0;39m [main] [36mcom.jcabi.github.RtUser[0;39m - #json(): thrown java.lang.AssertionError(HTTP response status is not equal to 200:
404 Not Found [https://api.github.com/users/boluo408]
Server: GitHub.com
Date: Thu, 31 Mar 2016 15:58:52 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4729
X-RateLimit-Reset: 1459442941
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, repo, user
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: DDDE0D97:1805C:DA35060:56FD493A

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
Expected: HTTP response with status 200
     but: was <404 Not Found [https://api.github.com/users/boluo408]
Server: GitHub.com
Date: Thu, 31 Mar 2016 15:58:52 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4729
X-RateLimit-Reset: 1459442941
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, repo, user
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: DDDE0D97:1805C:DA35060:56FD493A

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}>) out of org.hamcrest.MatcherAssert#assertThat[20] in 10s
Exception in thread "main" java.lang.AssertionError: HTTP response status is not equal to 200:
404 Not Found [https://api.github.com/users/boluo408]
Server: GitHub.com
Date: Thu, 31 Mar 2016 15:58:52 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4729
X-RateLimit-Reset: 1459442941
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, repo, user
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: DDDE0D97:1805C:DA35060:56FD493A

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
Expected: HTTP response with status 200
     but: was <404 Not Found [https://api.github.com/users/boluo408]
Server: GitHub.com
Date: Thu, 31 Mar 2016 15:58:52 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4729
X-RateLimit-Reset: 1459442941
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, repo, user
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: DDDE0D97:1805C:DA35060:56FD493A

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:117)
	at com.jcabi.github.RtJson.fetch_aroundBody0(RtJson.java:77)
	at com.jcabi.github.RtJson$AjcClosure1.run(RtJson.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.github.RtJson.fetch(RtJson.java:77)
	at com.jcabi.github.RtUser.json_aroundBody14(RtUser.java:174)
	at com.jcabi.github.RtUser$AjcClosure15.run(RtUser.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.github.RtUser.json(RtUser.java:174)
	at com.githubor.GithubClient.getUserInformation(GithubClient.java:344)
	at com.githubor.GithubClient.main(GithubClient.java:510)
```

**Comment by linxingyun** [comment]
@yegor256

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@linxingyun but the user doesn't exist: https://github.com/boluo408 what kind of response do you expect?

**Comment by linxingyun** [comment]
Expected behavior would be no crash even the user is not existed. Could that return will null or throw the Exception? so that the caller could be able to handle that situation. Thanks a lot!

**Comment by linxingyun** [comment]
@yegor256  Thanks for help!

**Comment by yegor256** [comment]
@linxingyun but we do throw an exception :) or you want an exception with a better description?

**Comment by linxingyun** [comment]
@yegor256  Yeah, it throws an error. I have added error catch code in my project. Thanks!
