### ISSUE TITLE
Fetching user repos

### ISSUE THREAD

**Issue by dieffrei** [jcabi/jcabi-github#1263]
When I tried to fetch repos using ""

for (Repo repo : github.repos().iterate("")){
     System.out.println(repo);				
}

one error was throwed:

ain] INFO com.jcabi.http.request.BaseRequest - #fetch(GET api.github.com /): [200 OK] in 2s
javax.json.JsonException: Cannot read JSON array, found JSON object
	at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:122)
	at com.jcabi.http.response.JsonResponse$VerboseReader.readArray(JsonResponse.java:169)
	at com.jcabi.github.RtValuePagination$Items.fetch(RtValuePagination.java:211)
	at com.jcabi.github.RtValuePagination$Items.hasNext(RtValuePagination.java:185)
	at BitbucketTest.main(BitbucketTest.java:21)

**Comment by dmarkov** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@dieffrei this most likely was due to the temporary down time at GitHub API. Can you try again?
