### ISSUE TITLE
Class not found :(

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [jcabi/jcabi-github#1264]
Here is my current code:
```java
	public static void main(String[] args) {
		Github github = new RtGithub("<my personal secret>");
		Repo repo = github.repos().get(new Coordinates.Simple("Lexium-Tech/TrollCraft"));
		Issue issue;
		try {
			issue = repo.issues().create("How are you?", "Please tell me...");
			issue.comments().post("My first comment!");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
```
and these are my imports:
`
import com.jcabi.github.Coordinates;
import com.jcabi.github.Github;
import com.jcabi.github.Issue;
import com.jcabi.github.Repo;
import com.jcabi.github.RtGithub;`
and I get this error:
`Exception in thread "main" java.lang.NoClassDefFoundError: org/aspectj/lang/Signature
	at xyz.lexium.giapb.Giapb.main(Giapb.java:14)
Caused by: java.lang.ClassNotFoundException: org.aspectj.lang.Signature
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more`
 I am using java 8

**Comment by xXXIMMATTHEWXXx** [comment]
Fixed. But next error:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/jcabi/manifests/Manifests
	at com.jcabi.github.RtGithub.<clinit>(RtGithub.java:82)
	at xyz.lexium.giapb.Giapb.main(Giapb.java:14)
Caused by: java.lang.ClassNotFoundException: com.jcabi.manifests.Manifests
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more`

**Comment by xXXIMMATTHEWXXx** [comment]
Just ignore this. I should have read alittle further....
