### ISSUE TITLE
slf4j: loader constraint violation when used inside IntelliJ IDEA plugin

### ISSUE THREAD

**Issue by halirutan** [jcabi/jcabi-github#1315]
I have a GitHub auto-report and wanted to use this library. However, calling a thing as simple as

``` java
myGitHub = new RtGithub(new RtGithub(gitAccessToken).entry().through(RetryWire.class));
myRepository = myGitHub.repos().get(new Coordinates.Simple(gitUser, gitRepo));
myIssues = myRepository.issues();
```

throughs an exception. Can I do something about this?

``` java
loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:299)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at com.jcabi.log.Logger.logger(Logger.java:365)
	at com.jcabi.log.Logger.isDebugEnabled(Logger.java:260)
	at com.jcabi.log.Logger.debug(Logger.java:167)
	at com.jcabi.manifests.Manifests.load(Manifests.java:537)
	at com.jcabi.manifests.Manifests.load(Manifests.java:504)
	at com.jcabi.manifests.Manifests.load(Manifests.java:445)
	at com.jcabi.manifests.Manifests.<clinit>(Manifests.java:155)
	at com.jcabi.github.RtGithub.<clinit>(RtGithub.java:82)
	at de.halirutan.mathematica.errorreporting.AnonymousFeedback.<init>(AnonymousFeedback.java:52)
	at de.halirutan.mathematica.errorreporting.AnonymousFeedbackTask.run(AnonymousFeedbackTask.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@halirutan seems like a conflict of dependencies. What I would try to do is to exclude slf4j dependency from jcabi-github. Something like this in your `pom.xml`:

```xml
<dependency>
  <groupId>com.jcabi</groupId>
  <artifactId>jcabi-github</artifactId>
  <exclusions>
    <exclusion>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

It seems that you have conflicts of dependencies.

**Comment by halirutan** [comment]
I don't use Maven for building, but I basically tried exactly this. I downloaded the basic jar and all its dependencies. Then I deleted the `slf4j.jar` from the libraries and forced the usage of  IDEA's `slf4.jar` with the same result. 

Since I need only a few lines of GitHub communication code, I move on the `egit` library. I thought I should still create an issue for this.

**Comment by amir1376** [comment]
any updates ?
