### ISSUE TITLE
Incorrect hasName implementation

### ISSUE THREAD

**Issue by g4s8** [jcabi/jcabi-github#1495]
Github API returns `null` as `name` JSON field if user doesn't have a name, but `User.Smart#hasName` implementation doesn't check it:
```java
public boolean hasName() throws IOException {
    return this.json().containsKey("name");
}
``` 
So when I check that user has a name and then read this name I'm getting an error:
```
java.lang.ClassCastException: javax.json.JsonValueImpl cannot be cast to javax.json.JsonString
    at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
    at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
    at com.jcabi.github.User$Smart.name_aroundBody8(User.java:191)
    at com.jcabi.github.User$Smart$AjcClosure9.run(User.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
    at com.jcabi.github.User$Smart.name(User.java:181)
```
(https://github.com/zerocracy/farm/issues/1753).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@g4s8 please provide a PR, there are no DEVs on the project and I don't really have time for it now.

I'll release it afterwards. Thanks!

**Comment by amihaiemil** [comment]
@g4s8 do you still have this issue, care to provide a PR? :D
