### ISSUE TITLE
RepoCommit.Smart#isVerified() is broken

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-github#1531]
```
java.lang.NullPointerException
	at com.jcabi.github.RepoCommit$Smart.isVerified(RepoCommit.java:134)
	at com.rultor.profiles.GithubProfile.checkTrustees(GithubProfile.java:242)
	at com.rultor.profiles.GithubProfile.asset(GithubProfile.java:201)
	at com.rultor.profiles.GithubProfile.assets(GithubProfile.java:143)
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.1.1`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1531` is not assigned, can't get performer

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue
