### ISSUE TITLE
Error while creating Gist

### ISSUE THREAD

**Issue by tzulberti-zendesk** [jcabi/jcabi-github#1557]
I am creating a gist using the following example:

```
Github github = new RtGithub(token);
var gist = github.gists().create(Map.of("foo.py", "this is an example"), false);
```

But the response from Github is the following one:
```
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/gists#create-a-gist"}>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
        at com.jcabi.github.RtGists.create(RtGists.java:113)
        at com.zendesk.changelog.output.GhGistOutput.print(GhGistOutput.java:24)
        at com.zendesk.changelog.Main.main(Main.java:37)
```

I checked this with version 0.41 mentioned [here](https://github.jcabi.com/) and the latest 1.1.2 release version

**Comment by tzulberti-zendesk** [comment]
This was related to an issue with the OUATH key that I was using. Not to the code itself.
