### ISSUE TITLE
Get all users using API v3?

### ISSUE THREAD

**Issue by maxbrito** [jcabi/jcabi-github#762]
Hi,

Is the jcabi implementing support to list all users?

The feature is listed:
https://developer.github.com/v3/users/#get-all-users

Test example: https://api.github.com/users?since=135

**Comment by arjunvijayvargiya** [comment]
Hi @yegor256 
I am getting the following error. How to go about this?
Exception in thread "main" java.lang.ClassCastException: org.glassfish.json.JsonNumberImpl$JsonIntNumber cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:194)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199)
	at com.jcabi.github.RtUsers$1.map(RtUsers.java:115)
	at com.jcabi.github.RtUsers$1.map(RtUsers.java:112)
	at com.jcabi.github.RtValuePagination$Items.next(RtValuePagination.java:172)
	at Main.main(Main.java:19)

**Comment by arjunvijayvargiya** [comment]
@nunobrito  can you please share your working code

**Comment by yegor256** [comment]
@arjunvijayvargiya it's better to submit a new issue for the problem you're having. Keep in mind that tickets are not chats :) They are for solving problems, one by one, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by nunobrito** [comment]
This was solved with the full jar deployment. In the meanwhile no longer have the code available.

For me this can be closed.
