### ISSUE TITLE
Got an exception when trying to get contents

### ISSUE THREAD

**Issue by lthuangiang** [jcabi/jcabi-github#903]
Following `Contents.get()` method, we got an exception

``` java
final Repos repos = github().repos();
final Repo repo =  repos.get(new Coordinates.Simple("jcabi/jcabi-github"));
System.out.println(new Content.Smart(repo.contents().get("src/main/java/com/jcabi/github/Users.java")).url());
// #output https://api.github.com/repos/jcabi/jcabi-github/contents/src/main/java/com/jcabi/github/Users.java?ref=master
System.out.println(new Content.Smart(repo.contents().get("src/main/java/com/jcabi/github/mock")).url());
```

ERROR LOG

```
https://api.github.com/repos/jcabi/jcabi-github/contents/src/main/java/com/jcabi/github/Users.java?ref=master
[[0;37mINFO[m] main com.jcabi.http.request.BaseRequest: #fetch(GET api.github.com /repos/jcabi/jcabi-github/contents/src/main/java/com/jcabi/github/mock): [200 OK] in 2s

javax.json.JsonException: Cannot read JSON object, found JSON array
    at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:105)
    at com.jcabi.http.response.JsonResponse$VerboseReader.readObject(JsonResponse.java:159)
    at com.jcabi.github.RtContents.content(RtContents.java:266)
```

**Comment by darkled** [comment]
@dmarkov unfortunately, for the moment `jcabi-github` absolutely doesn't support processing of `JsonArray`'s.

The possible fix of this problem could be this snippet in `RtContents` (I can push it if it could make sense):
```java
    private Content content(final String path, final String ref)
        throws IOException {
        final String name = "ref";
        final JsonStructure jsonStructure =
            this.request.method(Request.GET).uri().path(path)
                .queryParam(name, ref).back().fetch().as(RestResponse.class)
                .assertStatus(HttpURLConnection.HTTP_OK).as(JsonResponse.class)
                .json().read();
        String contentPath = null;
        if (ValueType.ARRAY == jsonStructure.getValueType()) {
            contentPath = path;
        } else if (ValueType.OBJECT == jsonStructure.getValueType()) {
            contentPath = ((JsonObject) jsonStructure).getString("path");
        }
        return new RtContent(this.entry.uri().queryParam(name, ref).back(),
            this.owner, contentPath);
    }
```

But actually it leads for further problems because somewhere inside this method `com.jcabi.github.RtContent.json()` is invoked which has 170 usages in sources and will throw the same exception `javax.json.JsonException: Cannot read JSON object, found JSON array`.

So, it looks not possible to fix without the great refactoring of all those classes and I have no idea what to do with it within this issue.

**Comment by darkled** [comment]
@dmarkov please, assign this task to someone else.

**Comment by dmarkov** [comment]
> @dmarkov please, assign this task to someone else.

@darkled I will assign somebody else to this issue

**Comment by dmarkov** [comment]
@palyuga This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by palyuga** [comment]
@dmarkov Waiting for #968 here

**Comment by dmarkov** [comment]
> @dmarkov Waiting for #968 here

@palyuga OK, let's wait for #968

**Comment by dmarkov** [comment]
@lthuangiang #968 is closed, it was an impediment

**Comment by dmarkov** [comment]
@palyuga check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 17 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 added to your rating, current score is: -30

**Comment by dmarkov** [comment]
@palyuga you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 to your rating, your total score is -90
